spring:
  application:
    name: chinese-idioms-game
  threads:
    virtual:
      enabled: true
  ai:
    dashscope:
      chat:
        options:
          model: qwen-plus
          temperature: 0.1
io:
  github:
    llmagentbuilder:
      chatagent:
        name: 成语接龙
        description: 成语接龙游戏，下一个成语的首字必须和上一个成语的末字完全一样
        usageInstruction: 直接输入成语
        reActJson:
          systemInstructions: |
            你和用户玩成语接龙的游戏。对于用户输入的成语，首先检查该成语的第一个字是否是上一个成语的最后一个字，如果不是，告知用户。再检查用户输入的成语是否为合法的成语。如果不是，告知用户。如果是的话，对于用户输入的成语，给出一个以输入的成语的最后一个字作为起始的成语。只输出该成语本身。
        memory:
          enabled: false
        tools:
          config:
            readLocalFile:
              basePath: test_data/input
            writeLocalFile:
              basePath: test_data/output
            executePythonCode:
              workingDirectory: test_data/input